apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    typeName: InfluxDB
    typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
    access: proxy
    url: http://influx:8086/
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      defaultBucket: homeassistant
      httpMode: POST
      organization: MOSTR
      version: Flux
    readOnly: false